name: 'Auto Assign'
on: pull_request

permissions: {}

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: kentaro-m/auto-assign-action@ed73f90568ce37d22dbbd1a73983738fae329f53 # v1.2.6
