name: 'Test'

on: push

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3

      - name: setup node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version-file: ./.node-version

      - name: install
        run: npm install

      - name: build
        run: npm run build

      - name: test
        run: npm test

      - name: format check
        run: npm run format-check
